[workspace]
resolver = "2"
members = [
    "engit-core",
    "engit-cli",
]

[workspace.package]
version = "0.1.0"
edition = "2021"
license = "GPL-3.0-or-later"
repository = "https://github.com/gtvfx-contrib/gt-envoy_utils"

[workspace.dependencies]
clap = { version = "4", features = ["derive"] }
envoy-core = { git = "https://github.com/gtvfx-contrib/gt-envoy", tag = "v0.5.1", version = "=0.5.1" }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
serde_yaml = "0.9"
thiserror = "1"
