"""Create one platform-specific Envoy Utils release archive."""

from __future__ import annotations

import argparse
import json
import os
import shutil
import tarfile
import tempfile
import zipfile
from datetime import UTC, datetime
from pathlib import Path, PurePosixPath

REPO_ROOT = Path(__file__).resolve().parent.parent


def parseArguments() -> argparse.Namespace:
    """Parse release-packaging arguments.

    Returns:
        Parsed command-line options.

    """
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--version", required=True, help="Release version, including v prefix."
    )
    parser.add_argument("--target-name", required=True, help="Artifact target label.")
    parser.add_argument("--binary-dir", type=Path, required=True)
    parser.add_argument("--output-dir", type=Path, default=REPO_ROOT / "dist")
    parser.add_argument("--windows", action="store_true", help="Create a ZIP archive.")
    return parser.parse_args()


def copyReleaseFiles(
    bundle_root: Path,
    binary_directory: Path,
    version: str,
    windows: bool,
) -> None:
    """Populate a staged Envoy Utils bundle.

    Args:
        bundle_root: Destination corresponding to ``gt/envoy_utils/<version>``.
        binary_directory: Directory containing the Engit binary.
        version: Version written to the bundle marker.
        windows: Whether to package the Windows executable.

    """
    bundle_root.mkdir(parents=True)
    shutil.copytree(REPO_ROOT / ".envoy", bundle_root / ".envoy")
    shutil.copy2(REPO_ROOT / "LICENSE", bundle_root / "LICENSE")
    shutil.copy2(REPO_ROOT / "README.md", bundle_root / "README.md")

    marker_data = {
        "bndlid": "gt:envoy_utils",
        "name": "envoy_utils",
        "version": version,
        "published": datetime.now(UTC).isoformat(),
    }
    marker_path = bundle_root / ".bundle"
    marker_path.write_text(json.dumps(marker_data, indent=2) + "\n", encoding="utf-8")

    bin_directory = bundle_root / "bin"
    bin_directory.mkdir()
    suffix = ".exe" if windows else ""
    source = binary_directory / f"engit{suffix}"
    if not source.is_file():
        raise FileNotFoundError(f"Native executable not found: {source}")
    destination = bin_directory / f"engit{suffix}"
    shutil.copy2(source, destination)
    if not windows:
        destination.chmod(destination.stat().st_mode | 0o755)


def normalizeTarMetadata(member: tarfile.TarInfo) -> tarfile.TarInfo:
    """Make archive ownership and permissions host-independent.

    Args:
        member: Archive entry generated by :mod:`tarfile`.

    Returns:
        Normalized archive entry.

    """
    archive_path = PurePosixPath(member.name)
    is_executable = archive_path.parent.name == "bin" and archive_path.name == "engit"

    member.uid = 0
    member.gid = 0
    member.uname = "root"
    member.gname = "root"
    if member.isdir() or is_executable:
        member.mode = 0o755
    elif member.isfile():
        member.mode = 0o644
    return member


def writeArchive(
    staging_directory: Path,
    output_directory: Path,
    version: str,
    target_name: str,
    windows: bool,
) -> Path:
    """Write the staged tree as ZIP or compressed tar.

    Args:
        staging_directory: Directory containing the ``gt`` archive root.
        output_directory: Destination for the completed archive.
        version: Version used in the archive filename.
        target_name: Platform label used in the archive filename.
        windows: Whether to emit ZIP instead of ``tar.gz``.

    Returns:
        Completed archive path.

    """
    output_directory.mkdir(parents=True, exist_ok=True)
    base_name = f"envoy_utils-{version}-{target_name}"
    if windows:
        archive_path = output_directory / f"{base_name}.zip"
        with zipfile.ZipFile(archive_path, "w", zipfile.ZIP_DEFLATED) as archive:
            for source in sorted(staging_directory.rglob("*")):
                if source.is_file():
                    archive.write(
                        source, source.relative_to(staging_directory).as_posix()
                    )
        return archive_path

    archive_path = output_directory / f"{base_name}.tar.gz"
    with tarfile.open(archive_path, "w:gz") as archive:
        archive.add(
            staging_directory / "gt",
            arcname="gt",
            filter=normalizeTarMetadata,
        )
    return archive_path


def main() -> int:
    """Create one release archive.

    Returns:
        Process exit status.

    """
    options = parseArguments()
    binary_directory = options.binary_dir.resolve()
    output_directory = options.output_dir.resolve()

    with tempfile.TemporaryDirectory(prefix="envoy-utils-release-") as temporary_path:
        staging_directory = Path(temporary_path)
        bundle_root = staging_directory / "gt" / "envoy_utils" / options.version
        copyReleaseFiles(
            bundle_root, binary_directory, options.version, options.windows
        )
        archive_path = writeArchive(
            staging_directory,
            output_directory,
            options.version,
            options.target_name,
            options.windows,
        )

    print(os.fspath(archive_path))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
